# Generated by Django 3.1.1 on 2020-10-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='City',
        ),
    ]
