# Generated by Django 3.1.1 on 2020-10-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201019_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
