# Generated by Django 3.1.1 on 2020-10-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='wind',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
