# Generated by Django 3.1.1 on 2020-10-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20201019_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='AQI',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='city',
            name='co2',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='city',
            name='maxCo2',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='city',
            name='minCo2',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='city',
            name='so2',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.IntegerField(default='000'),
        ),
    ]
