# Generated by Django 3.1.1 on 2020-10-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201019_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='maxSo2',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='city',
            name='minSo2',
            field=models.IntegerField(default='000'),
        ),
    ]
