# Generated by Django 3.1.1 on 2020-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20201019_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='humidity',
            field=models.IntegerField(default='000'),
        ),
    ]
