# Generated by Django 3.1.1 on 2020-11-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_city_humidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='maxCo2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='maxSo2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='minCo2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='minSo2',
        ),
        migrations.AddField(
            model_name='city',
            name='n',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='city',
            name='pm10',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='city',
            name='pm25',
            field=models.IntegerField(default='000'),
        ),
    ]
